export const APISUCCESS = Symbol('APISUCCESS')
export const APIFAIL = Symbol('APIFAIL')
export const APIPENDING = Symbol('APIPENDING')
export const APICLEAR = Symbol('APICLEAR')
export const SETTOKEN = Symbol('SETTOKEN')
export const CLEARTOEKN = Symbol('CLEARTOEKN')